local component = require("component")
local screen = component.list("screen")()
local gpu = component.proxy(component.list("gpu")())
assert(screen and gpu, "GPU or screen component missing")
assert(gpu.bind(screen), "unable to bind GPU to screen")
local width, height = gpu.getResolution()
gpu.setBackground(0x000000)
gpu.setForeground(0xFFFFFF)
gpu.fill(1, 1, width, height, " ")
gpu.set(2, 2, "GPU OK - direct OpenComputers rendering works")
